# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest
 service:
 - docker:dind
before_script:
  - export IMAGE_TAG=$CI_REGISTRY_IMAG:$(git rev-parse --short=8 $CI_COMMIT_SHA)

build-mater:
  stage: build
  tags:
   - master-shell
   - docker
  script:
#    - export IMAGE_TAG=dockeryanxiao/$CI_REGISTRY_IMAG:$CI_COMMIT_REF_NAME
#    - export IMAGE_TAG=$CI_REGISTRY_IMAG:$(git rev-parse --short=8 $CI_COMMIT_SHA)
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" 
    - docker build -t "$IMAGE_TAG" .
    - docker push "$IMAGE_TAG"
  only:
    - master
  
build-deploy:
  stage: deploy
  tags:
   - master-shell
  script:
    - id
    - who
    - kubectl apply -f alertmanger-k8s.yaml -n prod
  only:
    - master

#build:
#  stage: build
#  script:
#    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
#    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
#  except:
#    - master
