# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

services:
  - docker:dind


before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" 
  - export IMAGE_TAG=dockeryanxiao/$CI_REGISTRY_IMAG:$CI_COMMIT_REF_NAME
  tags:
   - docker


build-master:
  stage: build
  tags:
   - docker
  script:
    - docker build -t "$IMAGE_TAG" .
    - docker push "$IMAGE_TAG"
  only:
    - master
  
build-master:
  stage: deploy
  tags:
   - master-shell
  script:
    - sudo kubectl apply -f alertmanger-k8s.yaml
  only:
    - master

build:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  except:
    - master
